MVP Contract Implementation
ScopeLift/zeneth pull request #3
Opened 2021-04-28 16:55 UTC by apbendi

2021-04-29 23:50 UTC, mds1 reviewed
Didn't look at the tests closely, just took a quick review with lots of small comments

2021-04-29 23:50 UTC, mds1 commented on contracts/contracts/SwapBriber.sol
> +import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
`SafeERC20` imports this, so you can remove this to save an import if you want

2021-04-29 23:50 UTC, mds1 commented on contracts/contracts/SwapBriber.sol
> +        IUniswapV2Router02 _router, // better to keep this in storage?
Does Uniswap V3 have the same swap interface? If so maybe we keep this as an input

2021-04-29 23:50 UTC, mds1 commented on contracts/contracts/SwapBriber.sol
> +        SafeERC20.safeTransferFrom(_token, msg.sender, address(this), _tokenAmount);
Nit, but I find the `using SafeERC20 for IERC20` and `token.safeTransferFrom(...)` syntax easier to read since it keeps the usual `transferFrom` interface

2021-04-29 23:50 UTC, mds1 commented on contracts/contracts/SwapBriber.sol
> +        _token.approve(address(_router), _tokenAmount); // Can probably make this more efficient by only approving first time per token
Should use SafeERC0's `safeApprove` here to avoid issues like explained in [this](https://twitter.com/msolomon44/status/1377349391103586306) Twitter thread

2021-04-29 23:50 UTC, mds1 commented on contracts/contracts/SwapBriber.sol
> +    fallback() external payable { }
I think the recommended default is to use `receive() external payable { ... }` now?

2021-04-29 23:50 UTC, mds1 commented on contracts/test/SwapBriber.ts
> +  const bribeEth = tokenPrice.mul(bribeTokens).div(100).mul(95);
Upgrade to the most recent ethers version then try BigInt, it's so much more fun to do math that way 😁

2021-05-03 11:10 UTC, apbendi commented on contracts/contracts/SwapBriber.sol
> +        IUniswapV2Router02 _router, // better to keep this in storage?
At quick glance, it seems the router is quite different, so we'd need a new contract to support v3. SushiSwap router is compatible, though.

2021-05-04 11:13 UTC, apbendi commented on contracts/test/SwapBriber.ts
> +  const bribeEth = tokenPrice.mul(bribeTokens).div(100).mul(95);
Good idea! Created an issue for this: #5

2021-05-04 13:01 UTC, mds1 requested changes
Looks great! A few more comments, nothing major though, especially since we know it all works on Goerli already 🥳

2021-05-04 14:08 UTC, apbendi commented on contracts/contracts/SwapBriber.sol
> +        block.coinbase.transfer(_ethBribe);
The second param in `swapExactTokensForETH` is the minimum output amount. If the trade can't be executed for at least that amount, Uniswap should revert with a clear error: https://github.com/Uniswap/uniswap-v2-periphery/blob/master/contracts/UniswapV2Router02.sol#L293

2021-05-04 14:14 UTC, apbendi commented on contracts/contracts/SwapBriber.sol
> +            );
We have to call `allowance` to check whether the approval needs to happen. Calling `safeApprove` will call `allowance` again resulting in redundant state reads for a condition that can't occur. So in short, yes, this is a gas optimization. Will add some comments!

2021-05-04 14:14 UTC, apbendi commented on contracts/contracts/SwapBriber.sol
> +    function _callOptionalReturn(IERC20 token, bytes memory data) private {
`_callOptionalReturn` is marked as private by the OZ contracts

2021-05-04 14:16 UTC, mds1 commented on contracts/contracts/SwapBriber.sol
> +    function _callOptionalReturn(IERC20 token, bytes memory data) private {
Darn, well that is annoying haha

2021-05-04 14:21 UTC, apbendi commented on contracts/test/SwapBriber.ts
> +const UniswapV2Router02Artifact = require('@uniswap/v2-periphery/build/UniswapV2Router02.json');
Results in the following TS error:

```
Cannot find module '@uniswap/v2-core/build/UniswapV2Factory.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.ts(2732)
```

Created the following issue to track it separately #7

2021-05-04 14:38 UTC, merged